name = "PkgA"
uuid = "ae4a154e-1ddb-4467-9ee9-a6440ed2f538"
authors = ["Eric Hanson <5846501+ericphanson@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
Dates = "1.6"
Pkg = "1.6"
Test = "1.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
